spring:
  application:
    name: member-service
  config:
    import:
     - 'optional:configserver:http://3.38.80.105:9100'
  cloud:
    config:
      discovery:
        enabled: false
        #service-id: ${CLOUD_SERVICE_ID}

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_HOSTNAME}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

# 키클록 config 설정
keycloak:
  admin:
    server-url: https://auth.athenhub.xyz/
    realm: athenhub-dev
    client-id: athenhub-web
    client-secret: ${CLIENT_SECRET}

# OPEN DOC API 설정
springdoc:
  version: '1.0.0'
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs.html
    disable-swagger-default-url: true
    doc-expansion: full
  paths-to-match:
    - /**

openapi:
  service:
    url: http://localhost:9000